name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate syncing

      # Step 2: Set up SSH key
      - name: Set up SSH key
        run: |
          echo "${{ secrets.HUGGINGFACE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # Step 3: Add Hugging Face remote
      - name: Add Hugging Face remote
        run: git remote add space git@huggingface.co:spaces/gfeng321/demo.git

      # Step 4: Push to Hugging Face Spaces
      - name: Push to Hugging Face Spaces
        run: git push --force space main
